{
 "title": "Climas España",
 "description": "Panel para ver datos climáticos de las principales provincias en España.",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura Máxima - Madrid",
   "type": "stat",
   "description": "Temperatura máxima en Madrid de las últimas 24 horas.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "trimEdges": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "temperatura.actual", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Temperatura Mínima Madrid",
   "type": "stat",
   "description": "Temperatura máxima en Madrid.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "temperatura.actual", "id": "1", "type": "min" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Diferencia Temperatura - Madrid, Barcelona, Valencia",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Madrid",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "temperatura.actual", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Barcelona",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "temperatura.actual", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Valencia",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "temperatura.actual",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Sensación térmica Vs Temperatura real - Madrid",
   "type": "timeseries",
   "description": "Gráfica que compara la sensación de temperatura con la temperatura actual.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "temperatura.sensacion",
       "id": "1",
       "settings": {},
       "type": "avg"
      },
      {
       "field": "temperatura.actual",
       "hide": false,
       "id": "3",
       "settings": {},
       "type": "avg"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Frecuencia de Condiciones Meteorológicas - Valencia",
   "type": "piechart",
   "description": "Gráfico que muestra el porcentaje de tipo de clima.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "clima.description.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Humedad Relativa",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "Valencia",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "humedad", "id": "1", "type": "avg" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Barcelona",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "humedad", "id": "1", "type": "avg" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Madrid",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "humedad", "id": "1", "type": "avg" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Presión Atmosférica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    {
     "alias": "Valencia",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "presion", "id": "1", "type": "min" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Madrid",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "presion", "id": "1", "type": "min" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Barcelona",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "presion",
       "id": "1",
       "settings": {},
       "type": "min"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Velocidad Media Viento",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Barcelona",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "viento.speed", "id": "1", "type": "avg" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Madrid",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "viento.speed", "id": "1", "type": "avg" }
     ],
     "timeField": "timestamp"
    },
    {
     "alias": "Valencia",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "viento.speed", "id": "1", "type": "avg" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Madrid, Barcelona, Valencia - Temperatura Actual",
   "type": "timeseries",
   "description": "Madrid - Verde\nBarcelona - Amarillo\nValencia - Azul",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "temperatura.actual", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "temperatura.actual", "id": "1", "type": "max" }
     ],
     "timeField": "timestamp"
    },
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "temperatura.actual",
       "id": "1",
       "settings": {},
       "type": "max"
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Sensación Térmica Vs Temperatura Actual - Madrid",
   "type": "timeseries",
   "description": "Gráfica que compara la sensación de temperatura con la temperatura actual.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "temperatura.sensacion",
       "id": "1",
       "settings": {},
       "type": "avg"
      },
      { "field": "temperatura.actual", "id": "3", "type": "avg" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Sensación Térmica Vs Temperatura Actual - Madrid",
   "type": "timeseries",
   "description": "Gráfica que compara la sensación de temperatura con la temperatura actual.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "temperatura.sensacion",
       "id": "1",
       "settings": {},
       "type": "avg"
      },
      { "field": "temperatura.actual", "id": "3", "type": "avg" }
     ],
     "timeField": "timestamp"
    }
   ]
  }
 ]
}